# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       ultimate-tictactoe

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Ultimate Tic-Tac-Toe with AI opponents
Version:    0.1
Release:    1
Group:      Games/BoardGame
License:    LICENSE
Source0:    %{name}-%{version}.tar.bz2
#Source100:  ultimate-tictactoe.yaml
Requires:   qt5-qtcore
Requires:   qt5-qtgui
Requires:   qt5-qtdeclarative
BuildRequires:  qt5-qtcore-devel
BuildRequires:  qt5-qtgui-devel
BuildRequires:  qt5-qtdeclarative-devel
BuildRequires:  desktop-file-utils

%description
Ultimate Tic-Tac-Toe with AI opponents


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
/usr/share/icons/hicolor/90x90/apps
/usr/share/applications
/usr/share/ultimate-tictactoe
/usr/bin
%{_datadir}/icons/hicolor/90x90/apps/%{name}.png
%{_datadir}/applications/%{name}.desktop
%{_datadir}/%{name}/qml
%{_bindir}
/opt/ultimate-tictactoe/bin
/opt/ultimate-tictactoe/qml
# >> files
# << files
